### ISSUE TITLE
Error while trying to log in from Anki

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [bewuwy/Neo-Anki-Leaderboard#3]
Describe your issue:

Tried to log 2 times, first with pseudo + pwd, then with email + pwd, but resulted 2 times in an Anki error modal.

Anki version:
Version ⁨2.1.54 (b6a7760c)⁩
Python 3.9.7 Qt 6.3.1 PyQt 6.3.1

On Windows 10

Debug log:
```
NeoLeaderBoard addon loaded
version: 0.4.9
folder: 1894428367

User not logged in and tried to sync
Logged in user 5jg7gecr644w89y
Logged in successfully
full sync
Error syncing review count to NAL. See log for details
Traceback (most recent call last):
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\hooks.py", line 72, in on_anki_sync
    mw.NAL_PB.user.set_reviews(datetime.datetime.utcnow(), r)
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 131, in set_reviews
    curr_reviews = self.get_reviews()
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 124, in get_reviews
    curr_reviews = data["reviews"]
KeyError: 'reviews'

Logged in user 5jg7gecr644w89y
Logged in successfully
full sync
Error syncing review count to NAL. See log for details
Traceback (most recent call last):
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\hooks.py", line 72, in on_anki_sync
    mw.NAL_PB.user.set_reviews(datetime.datetime.utcnow(), r)
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 131, in set_reviews
    curr_reviews = self.get_reviews()
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 124, in get_reviews
    curr_reviews = data["reviews"]
KeyError: 'reviews'

```

**Comment by bewuwy** [comment]
The user_data is only initialized when loading login from data, so that's why this happens I think.

@Crazy-Unicooorn Try relaunching Anki and this should work for now. 

I will update to fix this issue.

**Comment by Crazy-Unicooorn** [comment]
I relaunched Anki a couple times and tried again, still gives the error. Am I supposed to try differently?
Here is the error Anki gave me, I think it looks a little bit different now?

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-03-03 11:23:08

Caught exception:
Traceback (most recent call last):
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\login.py", line 49, in on_login_user
    op=login_user(user, password),
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\login.py", line 75, in login_user
    mw.NAL_PB.user.full_sync()
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 269, in full_sync
    return self.set_multiple_reviews(reviews)
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 148, in set_multiple_reviews
    curr_reviews = self.get_reviews()
  File "C:\Users\{user}\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 124, in get_reviews
    curr_reviews = data["reviews"]
KeyError: 'reviews'
```

**Comment by bewuwy** [comment]
now it should work

**Comment by Crazy-Unicooorn** [comment]
Yup it does! Thanks for a quick fix :)

**Comment by bewuwy** [comment]
np
