### ISSUE TITLE
Error right after login

### ISSUE THREAD

**Issue by 906bc906** [bewuwy/Neo-Anki-Leaderboard#4]
## Summary

An error occurs when I log in with Anki for windows.

Manual Sync doesn't send my review data to the server.

![image](https://user-images.githubusercontent.com/57206558/234162151-a181f2cf-3a06-4624-98c5-e084dafef7b9.png)
Disabled all add-ons but NAL.

### When I just launch Anki
Debug Log:
```
2023-04-25 02:35:27: NeoLeaderBoard addon loaded
2023-04-25 02:35:27: version: 0.6.1
2023-04-25 02:35:27: folder: 1894428367
2023-04-25 02:35:29: User not logged in and tried to sync
```

### Login
![image](https://user-images.githubusercontent.com/57206558/234161150-9753963b-4aea-4404-8ccc-1b1329242953.png)

Error after pressing the OK button:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.61 (0c1eaf4c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-04-25 11:26:59

Caught exception:
Traceback (most recent call last):
  File "C:\Users\906bc\AppData\Roaming\Anki2\addons21\1894428367\login.py", line 49, in on_login_user
    op=login_user(user, password),
  File "C:\Users\906bc\AppData\Roaming\Anki2\addons21\1894428367\login.py", line 76, in login_user
    mw.NAL_PB.user.full_sync()
  File "C:\Users\906bc\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 354, in full_sync
    return self.update_pb_data(reviews, curr_streak=streak["current"], highest_streak=streak["highest"])
  File "C:\Users\906bc\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 205, in update_pb_data
    curr_data["reviews"][rev_keys] = reviews[rev_keys]
TypeError: 'NoneType' object does not support item assignment
```

Debug log:
```
2023-04-25 02:35:27: NeoLeaderBoard addon loaded
2023-04-25 02:35:27: version: 0.6.1
2023-04-25 02:35:27: folder: 1894428367
2023-04-25 02:35:29: User not logged in and tried to sync
2023-04-25 02:38:42: Logged in user 2wpyfipvelgapot
2023-04-25 02:38:48: Logged in successfully
2023-04-25 02:38:48: Full sync start
2023-04-25 02:38:48: 32 days with reviews found
2023-04-25 02:38:48: {'current': 0, 'highest': 8} days streak
```

### Sync manually

Debug log after sync:
```
2023-04-25 02:35:27: NeoLeaderBoard addon loaded
2023-04-25 02:35:27: version: 0.6.1
2023-04-25 02:35:27: folder: 1894428367
2023-04-25 02:35:29: User not logged in and tried to sync
2023-04-25 02:38:42: Logged in user 2wpyfipvelgapot
2023-04-25 02:38:48: Logged in successfully
2023-04-25 02:38:48: Full sync start
2023-04-25 02:38:48: 32 days with reviews found
2023-04-25 02:38:48: {'current': 0, 'highest': 8} days streak
2023-04-25 02:40:19: Error syncing review count to NAL. See log for details
2023-04-25 02:40:19: Traceback (most recent call last):
  File "C:\Users\906bc\AppData\Roaming\Anki2\addons21\1894428367\hooks.py", line 71, in on_anki_sync
    mw.NAL_PB.user.sync()
  File "C:\Users\906bc\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 336, in sync
    self.update_pb_data(reviews)
  File "C:\Users\906bc\AppData\Roaming\Anki2\addons21\1894428367\pocketbase_api.py", line 205, in update_pb_data
    curr_data["reviews"][rev_keys] = reviews[rev_keys]
TypeError: 'NoneType' object does not support item assignment
```

**Comment by yitzhakbg** [comment]
Same problem on Mac with Anki 2.1.64.
Kudos on the fine job you're doing
